; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Jan 14 2021 17:26:13 GMT+0000 (Greenwich Mean Time)
; ================================================================================

DATA07SCXMZCAVSG:
	dc.w DATA07SCXMZCAVSG_0-DATA07SCXMZCAVSG
DATA07SCXMZCAVSG_0: dc.b $1
	dc.b $0, $8, $0, $0, $F1
	even